include_dirs = [ include_directories('../..') ]

headers = files(
  'attrs.hh',
  'cache.hh',
  'fetch-settings.hh',
  'fetch-to-store.hh',
  'fetchers.hh',
  'filtering-source-accessor.hh',
  'git-lfs-fetch.hh',
  'git-typed.hh',
  'git-utils.hh',
  'github-typed.hh',
  'input-cache.hh',
  'registry.hh',
  'tarball-typed.hh',
  'tarball.hh',
  'typed-inputs.hh',
)
