installing 'outputsToInstall-with-context-1.0'
this derivation will be built:
  /test-root/store/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-outputsToInstall-with-context-1.0.drv
building '/test-root/store/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-outputsToInstall-with-context-1.0.drv'...
error:
       error: the string '/test-root/store/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-normal-1.0' is not allowed to refer to a store path (such as '/test-root/store/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-normal-1.0.drv^out')
