error:
       … while querying the derivation named 'bad-output-type-1.0'

       … while evaluating an output of a derivation
         at /pwd/cli-characterisation/bad-output-type.nix:5:3:
            4|   outPath = builtins.toFile "out" "";
            5|   outputs = [ "foo" ];
             |   ^
            6|   foo = "not-an-attrset";

       error: expected a set but found a string: "not-an-attrset"
